language: python
python:
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
script:
  - coverage run --source=com/bruno/ -m unittest discover;coverage 
  - python -m unittest discover
