language: python
python:
        - 3.7

before_install:
        - python --version
        - pip install -U pip
        - pip install codecov

scrip:
        - coverage run --source=com/bruno/ -m unittest discover;coverage report -m
        - python -m unittest discover
